#!/usr/bin/env python3
"""Start a backtest grid on the Step Functions state machine, straight from S3.

One command, no manual download / JSON wrapping / ARN lookup:

  python scripts/start_backtest.py --grid s3://nexusquant-data/backtest-configs/griglia.json
  python scripts/start_backtest.py --grid s3://nexusquant-data/backtest-configs/griglia.json --limit 1 --wait
  python scripts/start_backtest.py --grid backtest/griglia.json --dry-run

--grid accepts s3://bucket/key or a local path. The file may be a JSON list of
configs (like the one used with --grid in the CLI), {"configs": [...]}, or a
single config object. Uses your normal AWS CLI credentials.

Requires: pip install boto3
"""
from __future__ import annotations

import argparse
import json
import sys
import time
import uuid

MAX_PAYLOAD_BYTES = 250_000  # Step Functions input limit is 256 KiB
INLINE_MAP_SOFT_LIMIT = 400  # ~25k history events per execution (inline Map)


def load_grid(src: str, region: str):
    if src.startswith("s3://"):
        import boto3

        bucket, _, key = src[5:].partition("/")
        if not bucket or not key:
            sys.exit(f"Invalid S3 URI: {src}")
        body = boto3.client("s3", region_name=region).get_object(Bucket=bucket, Key=key)["Body"].read()
        return json.loads(body)
    with open(src, encoding="utf-8-sig") as f:
        return json.load(f)


def to_configs(data) -> list[dict]:
    if isinstance(data, dict) and isinstance(data.get("configs"), list):
        data = data["configs"]
    elif isinstance(data, dict):
        data = [data]
    if not isinstance(data, list) or not data:
        sys.exit("The grid must be a non-empty JSON list of configs (or {\"configs\": [...]}).")
    if not all(isinstance(c, dict) for c in data):
        sys.exit("Every config must be a JSON object.")
    return data


def validate(configs: list[dict]) -> None:
    names = [c.get("name") for c in configs]
    if any(not n for n in names):
        sys.exit("Every config needs a non-empty 'name' (retries are idempotent on run_group_id + name).")
    dup = sorted({n for n in names if names.count(n) > 1})
    if dup:
        sys.exit(f"Duplicate config names (must be unique in a run): {dup}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--grid", required=True, help="s3://bucket/key.json or local path")
    p.add_argument("--project", default="nexusquant")
    p.add_argument("--env", default="dev")
    p.add_argument("--region", default="eu-north-1")
    p.add_argument("--limit", type=int, help="run only the first N configs (smoke test)")
    p.add_argument("--name", action="append", help="run only the config(s) with this name (repeatable)")
    p.add_argument("--run-group-id", help="reuse an existing run group UUID (default: generated by the state machine)")
    p.add_argument("--wait", action="store_true", help="poll until the execution finishes")
    p.add_argument("--dry-run", action="store_true", help="validate and print, do not start anything")
    a = p.parse_args()

    configs = to_configs(load_grid(a.grid, a.region))
    if a.name:
        configs = [c for c in configs if c.get("name") in set(a.name)]
        if not configs:
            sys.exit(f"No config matches --name {a.name}")
    if a.limit:
        configs = configs[: a.limit]
    validate(configs)

    payload: dict = {"configs": configs}
    if a.run_group_id:
        payload["run_group_id"] = str(uuid.UUID(a.run_group_id))  # validates the UUID
    body = json.dumps(payload)
    if len(body.encode()) > MAX_PAYLOAD_BYTES:
        sys.exit(f"Input is {len(body)} bytes (> {MAX_PAYLOAD_BYTES}): split the grid in several runs.")
    if len(configs) > INLINE_MAP_SOFT_LIMIT:
        print(f"WARNING: {len(configs)} configs; above ~{INLINE_MAP_SOFT_LIMIT} per execution the history limit may be hit. "
              "Split in several runs sharing --run-group-id.", file=sys.stderr)

    print(f"{len(configs)} config(s): " + ", ".join(c["name"] for c in configs))
    if a.dry_run:
        print(f"dry-run OK ({len(body)} bytes), nothing started.")
        return

    import boto3

    account = boto3.client("sts", region_name=a.region).get_caller_identity()["Account"]
    sm_arn = f"arn:aws:states:{a.region}:{account}:stateMachine:{a.project}-backtest-{a.env}"
    sfn = boto3.client("stepfunctions", region_name=a.region)
    ex = sfn.start_execution(stateMachineArn=sm_arn, input=body)["executionArn"]
    print("started:", ex)
    print(f"console: https://{a.region}.console.aws.amazon.com/states/home?region={a.region}#/v2/executions/details/{ex}")

    if not a.wait:
        return
    while True:
        d = sfn.describe_execution(executionArn=ex)
        if d["status"] != "RUNNING":
            break
        time.sleep(15)
    print("status:", d["status"])
    if d.get("output"):
        out = json.loads(d["output"])
        for r in out.get("results", []):
            print("  config #%s: %s" % (r.get("index"), r.get("status")), r.get("error", ""))
    if d.get("error"):
        print("error:", d["error"], "-", d.get("cause", ""))
    sys.exit(0 if d["status"] == "SUCCEEDED" else 1)


if __name__ == "__main__":
    main()
